name: 🧪 Тесты для my_service

on:
  push:
    paths:
      - "clientservice/my_service/**"
      - ".github/workflows/test-my-service.yml"
  pull_request:
    paths:
      - "clientservice/my_service/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Клонирование репозитория
        uses: actions/checkout@v4

      - name: 🐍 Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r clientservice/my_service/requirements.txt
          pip install pytest pytest-cov

      - name: 🧪 Запуск тестов с покрытием
        run: |
          PYTHONPATH=clientservice/my_service pytest \
            --cov=app \
            --cov-report=term \
            --cov-report=xml \
            clientservice/my_service/tests

      - name: 📤 Отправка покрытия в Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: my-service
          name: codecov-my-service