version: '3.8'

services:
  auth:
    build:
      context: ./clientservice/auth
    container_name: auth
    ports:
      - "5051:5001"
    volumes:
      - ./clientservice/auth:/app
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/auth/verify"]
      interval: 10s
      timeout: 5s
      retries: 5

  chat:
    build:
      context: ./clientservice/chat
    container_name: chat
    ports:
      - "5052:5002"
    volumes:
      - ./clientservice/chat:/app
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    build:
      context: ./clientservice/worker
    container_name: worker
    ports:
      - "5050:8000"
    volumes:
      - ./shared/schemas:/app/shared/schemas
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started
      crm:
        condition: service_started
    environment:
      - PYTHONPATH=/app:/app/shared
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CFG_CLUSTER_ID=V4XjsoY1QkOz9mmoDLjSRA
      - ALLOW_PLAINTEXT_LISTENER=yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  crm:
    build:
      context: ./clientservice/crm
    container_name: crm
    ports:
      - "5053:5000"
    volumes:
      - ./clientservice/crm:/app
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  api_gateway:
    build:
      context: ./clientservice/api_gateway
    container_name: api_gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./clientservice/api_gateway:/app
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/apidocs"]
      interval: 10s
      timeout: 5s
      retries: 5

  my_service:
    build:
      context: ./clientservice/my_service
    container_name: my_service
    ports:
      - "5054:5004"
    volumes:
      - ./clientservice/my_service:/app
    environment:
      - PYTHONPATH=/app
    depends_on:
      kafka:
        condition: service_started
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5004/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  dashboard:
    build:
      context: ./clientservice/dashboard
    container_name: dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./clientservice/dashboard:/app
    command: streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: