version: '3.8'

services:
  # Сервис аутентификации (auth)
  auth:
    build:
      context: ./clientservice/auth
    container_name: auth
    ports:
      - "5051:5001"
    volumes:
      - ./clientservice/auth:/app
    environment:
      - PYTHONPATH=/app

  # Сервис чата (chat)
  chat:
    build:
      context: ./clientservice/chat
    container_name: chat
    ports:
      - "5052:5002"
    volumes:
      - ./clientservice/chat:/app
    environment:
      - PYTHONPATH=/app

  # Сервис обработки (worker)
  worker:
    build:
      context: ./clientservice/worker
    container_name: worker
    ports:
      - "5050:8000"
      - "5059:8000"
    volumes:
      - ./clientservice/worker:/app
      - ./shared/schemas:/app/shared/schemas
    depends_on:
      - kafka
      - crm
    environment:
      - PYTHONPATH=/app:/app/shared

  # Kafka брокер
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CFG_CLUSTER_ID=V4XjsoY1QkOz9mmoDLjSRA
      - ALLOW_PLAINTEXT_LISTENER=yes

  # Моковая CRM
  crm:
    build:
      context: ./clientservice/crm
    container_name: crm
    ports:
      - "5053:5000"
    volumes:
      - ./clientservice/crm:/app
    environment:
      - PYTHONPATH=/app

  # API Gateway
  api_gateway:
    build:
      context: ./clientservice/api_gateway
    container_name: api_gateway
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./clientservice/api_gateway:/app
    environment:
      - PYTHONPATH=/app

  # PostgreSQL база
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: client_user
      POSTGRES_PASSWORD: client_pass
      POSTGRES_DB: client_service
    ports:
      - "5432:5432"