summary: Создание новой задачи
tags:
  - Task
parameters:
  - in: body
    name: body
    required: true
    schema:
      $ref: '#/definitions/TaskCreate'
responses:
  201:
    description: Задача создана
    schema:
      $ref: '#/definitions/Task'
