summary: Получение списка задач
tags:
  - Task
responses:
  200:
    description: Список задач получен
    content:
      application/json:
        schema:
          type: array
          items:
            $ref: '#/definitions/Task'
