summary: Создание новой задачи
tags:
  - Task
requestBody:
  required: true
  content:
    application/json:
      schema:
        $ref: '#/definitions/TaskCreate'
responses:
  201:
    description: Задача успешно создана
    content:
      application/json:
        schema:
          $ref: '#/definitions/Task'
