summary: Удаление задачи по ID
tags:
  - Task
parameters:
  - name: task_id
    in: path
    required: true
    schema:
      type: integer
responses:
  200:
    description: Задача успешно удалена
    content:
      application/json:
        schema:
          type: object
          properties:
            message:
              type: string
