summary: Обновление задачи по ID
tags:
  - Task
parameters:
  - name: task_id
    in: path
    required: true
    schema:
      type: integer
requestBody:
  required: true
  content:
    application/json:
      schema:
        $ref: '#/definitions/TaskUpdate'
responses:
  200:
    description: Задача успешно обновлена
    content:
      application/json:
        schema:
          $ref: '#/definitions/Task'
