name: 🧪 Тесты для worker

on:
  pull_request:
    paths:
      - "client-worker/worker/**"
      - ".github/workflows/tests.yml"
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Клонирование репозитория
        uses: actions/checkout@v4

      - name: 🐍 Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r client-worker/worker/requirements.txt
          pip install pytest pytest-cov

      - name: 🧪 Запуск тестов с покрытием
        run: |
          PYTHONPATH=client-worker/worker pytest \
            --cov=app \
            --cov-report=term \
            --cov-report=xml \
            client-worker/worker/tests

      - name: 📤 Отправка покрытия в Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-client-worker
