name: 🧪 Тесты для worker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Клонировать репозиторий
      uses: actions/checkout@v4

    - name: 🐍 Установить Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: 📦 Установить зависимости
      run: |
        python -m pip install --upgrade pip
        pip install flask pytest flasgger kafka-python requests pytest-cov

    - name: ✅ Прогнать pytest с покрытием
      run: |
        PYTHONPATH=. pytest --cov=worker --cov-report=term --cov-report=xml worker/tests

    - name: 📤 Отправить покрытие в Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        fail_ci_if_error: true
