name: 🧪 Тесты для worker

on:
  pull_request:
    paths:
      - "clientservice/worker/**"
      - ".github/workflows/tests.yml"
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Клонирование репозитория
        uses: actions/checkout@v4

      - name: 🐍 Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r clientservice/worker/requirements.txt
          pip install pytest pytest-cov

      - name: 🧪 Запуск тестов с покрытием
        run: |
          PYTHONPATH=. pytest \
            --cov=clientservice.worker.app \
            --cov-report=term \
            --cov-report=xml \
            clientservice/worker/tests

      - name: 📤 Отправка покрытия в Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-client-worker

      - name: Проверка доступности Swagger UI
        run: |
          curl --fail http://localhost:5059/apidocs
          curl --fail http://localhost:8081/apidocs
          curl --fail http://localhost:8081/static/swagger-ui.html
          curl --fail http://localhost:8080/time-entries/