name: 🧪 Тесты для worker

on:
  pull_request:
    paths:
      - "clientservice/worker/**"
      - ".github/workflows/tests.yml"
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Клонирование репозитория
        uses: actions/checkout@v4

      - name: 🐍 Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Установка зависимостей
        run: |
          python -m pip install --upgrade pip
          pip install -r clientservice/worker/requirements.txt
          pip install -r clientservice/worker/requirements-dev.txt
          pip install pytest pytest-cov

      - name: ⚙️ Установка PYTHONPATH
        run: echo "PYTHONPATH=$PWD/clientservice:$PWD/clientservice/worker" >> $GITHUB_ENV

      - name: 🧪 Запуск тестов с покрытием
        run: |
          pytest clientservice/worker/tests \
            --cov=clientservice/worker/app \
            --cov-report=term \
            --cov-report=xml

      - name: 📤 Отправка покрытия в Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: unittests
          name: codecov-client-worker

      - name: ✅ Проверка доступности Swagger UI (опционально)
        run: |
          echo "⚠️ Swagger не запускается в этом воркфлоу без контейнеров"
          echo "Пропускаем проверку UI"