components:
  schemas:
    ErrorResponse:
      properties:
        error:
          example: Некорректный формат запроса
          type: string
      type: object
    LoginRequest:
      properties:
        password:
          type: string
        username:
          type: string
      required:
      - username
      - password
      type: object
    LoginResponse:
      properties:
        access_token:
          type: string
      type: object
    SendEventRequest:
      properties:
        client_id:
          type: string
        message:
          type: string
      required:
      - client_id
      - message
      type: object
    SendEventResponse:
      properties:
        status:
          example: ok
          type: string
      type: object
  securitySchemes:
    BearerAuth:
      bearerFormat: JWT
      description: 'Введите токен как: Bearer <токен>'
      scheme: bearer
      type: http
info:
  description: Client worker API с поддержкой JWT-аутентификации, Kafka и интеграции
    с CRM
  title: Client Worker API
  version: 1.0.0
openapi: 3.0.3
paths:
  /:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                type: object
          description: Сервис работает
      summary: Главная проверка сервиса
  /login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
          description: JWT токен выдан
        '401':
          description: Неверные данные
      summary: Авторизация пользователя
  /protected:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  logged_in_as:
                    type: string
                type: object
          description: Авторизован
        '401':
          description: Неавторизован
      security:
      - BearerAuth: []
      summary: Проверка авторизованного пользователя
  /send:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendEventRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SendEventResponse'
          description: Событие отправлено
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Ошибка формата запроса
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Ошибка сервера или Kafka
      security:
      - BearerAuth: []
      summary: Отправка события в Kafka
security:
- BearerAuth: []
servers:
- url: http://localhost:5050